"""
cortex/skills/creator.py — Automatic skill creation from usage patterns.

When Odysseus detects a repeated pattern (e.g. same sequence of codegen
operations 3+ times), it can create a reusable skill automatically.

Also supports manual creation from explicit definitions.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .registry import Skill, SkillRegistry, get_registry

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pattern detection
# ---------------------------------------------------------------------------


@dataclass
class PatternStep:
    """A single step in a detected usage pattern."""

    action: str  # e.g. "codegen.run", "patcher.create", "git.commit"
    description: str = ""
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class UsagePattern:
    """A recurring pattern extracted from trajectories."""

    name: str
    description: str
    steps: List[PatternStep] = field(default_factory=list)
    occurrence_count: int = 0
    avg_duration_ms: float = 0.0
    categories: List[str] = field(default_factory=list)
    trigger: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Skill creator
# ---------------------------------------------------------------------------


class SkillCreator:
    """Creates skills from usage patterns or explicit definitions."""

    def __init__(self, registry: Optional[SkillRegistry] = None):
        self._registry = registry or get_registry()

    # ------------------------------------------------------------------
    # Create from pattern
    # ------------------------------------------------------------------

    def from_pattern(self, pattern: UsagePattern) -> Skill:
        """Create a Skill from a detected UsagePattern.

        Args:
            pattern: The recurring pattern to codify as a skill

        Returns:
            A new Skill object (not yet installed)
        """
        steps_md = self._format_steps(pattern.steps)

        body = f"""## Description

{pattern.description}

This skill was auto-generated by Odysseus from {pattern.occurrence_count} observed uses.
Average duration: {pattern.avg_duration_ms:.0f}ms.

## Steps

{steps_md}

## Metadata

- **Auto-generated:** {datetime.now(timezone.utc).isoformat()}
- **Source pattern:** {pattern.name}
- **Occurrences:** {pattern.occurrence_count}
"""

        # Generate trigger phrases from pattern name
        if not pattern.trigger:
            trigger = self._infer_triggers(pattern.name, pattern.description)
        else:
            trigger = list(pattern.trigger)

        # Infer categories if not provided
        categories = list(pattern.categories) if pattern.categories else ["general"]

        return Skill(
            name=self._sanitize_name(pattern.name),
            description=pattern.description,
            version="0.1.0",
            author="odysseus-auto",
            tags=self._infer_tags(pattern),
            categories=categories,
            trigger=trigger,
            requires=[],
            body=body,
        )

    # ------------------------------------------------------------------
    # Create from codegen trajectory
    # ------------------------------------------------------------------

    def from_codegen_trajectory(
        self,
        task_description: str,
        files_written: List[str],
        provider: str,
        template: str = "next",
    ) -> Skill:
        """Create a skill from a successful codegen run.

        Captures the sequence: scaffold → plan → tool loop → git init
        so it can be replayed for similar tasks.
        """
        # Build trigger from task keywords
        words = re.findall(r"[a-z]+", task_description.lower())
        trigger = [" ".join(words[:3])] if len(words) >= 3 else [task_description[:30]]

        # Infer category
        category = "code_generation"
        if "doc" in task_description.lower():
            category = "documentation"
        elif "test" in task_description.lower():
            category = "testing"

        steps = [
            PatternStep(
                action="scaffold",
                description=f"Scaffold {template} starter",
                params={"template": template},
            ),
            PatternStep(
                action="codegen.run",
                description=f"Run codegen with {provider}",
                params={"provider": provider, "prompt": task_description[:200]},
            ),
            PatternStep(
                action="git.init",
                description="Initialize git repository",
                params={},
            ),
        ]

        pattern = UsagePattern(
            name=f"codegen-{'-'.join(words[:3])}",
            description=f"Auto-captured codegen pattern: {task_description[:100]}",
            steps=steps,
            occurrence_count=1,
            categories=[category],
            trigger=trigger,
        )

        return self.from_pattern(pattern)

    # ------------------------------------------------------------------
    # Create from explicit definition
    # ------------------------------------------------------------------

    def from_definition(
        self,
        name: str,
        description: str,
        body: str,
        tags: Optional[List[str]] = None,
        categories: Optional[List[str]] = None,
        trigger: Optional[List[str]] = None,
        requires: Optional[List[str]] = None,
        author: str = "odysseus",
    ) -> Skill:
        """Create a skill from an explicit definition."""
        return Skill(
            name=self._sanitize_name(name),
            description=description,
            version="0.1.0",
            author=author,
            tags=tags or [],
            categories=categories or ["general"],
            trigger=trigger or [],
            requires=requires or [],
            body=body,
        )

    # ------------------------------------------------------------------
    # Install + validate
    # ------------------------------------------------------------------

    def create_and_install(self, skill: Skill) -> Path:
        """Install a skill and validate its format."""
        self._validate(skill)
        return self._registry.install_skill(skill)

    def _validate(self, skill: Skill) -> None:
        """Validate a skill before installing.

        Raises ValueError if the skill is invalid.
        """
        if not skill.name:
            raise ValueError("Skill name is required")
        if not skill.description:
            raise ValueError("Skill description is required")
        if not skill.body:
            raise ValueError("Skill body is required")
        # Check name is filesystem-safe
        if not re.match(r"^[a-z0-9][a-z0-9-]*$", skill.name):
            raise ValueError(
                f"Invalid skill name '{skill.name}': must be lowercase, "
                "alphanumeric with hyphens only"
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _format_steps(steps: List[PatternStep]) -> str:
        """Format pattern steps as markdown numbered list."""
        if not steps:
            return "(no steps recorded)"
        lines = []
        for i, step in enumerate(steps, 1):
            line = f"{i}. **{step.action}** — {step.description}"
            if step.params:
                param_str = ", ".join(
                    f"`{k}={v}`" for k, v in step.params.items()
                )
                line += f" ({param_str})"
            lines.append(line)
        return "\n".join(lines)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Convert a name to a valid skill name."""
        sanitized = name.lower().strip()
        sanitized = re.sub(r"[^a-z0-9]+", "-", sanitized)
        sanitized = sanitized.strip("-")
        if not sanitized:
            sanitized = "unnamed-skill"
        return sanitized

    @staticmethod
    def _infer_triggers(name: str, description: str) -> List[str]:
        """Infer trigger phrases from name and description."""
        triggers: List[str] = []
        # Use first 3 words of name
        name_words = name.replace("-", " ").split()
        if name_words:
            triggers.append(" ".join(name_words[:3]))
        # Use keywords from description
        desc_words = re.findall(r"[a-z]+", description.lower())
        keywords = [w for w in desc_words if len(w) > 3][:3]
        if keywords:
            triggers.append(" ".join(keywords))
        return list(dict.fromkeys(triggers))  # dedupe

    @staticmethod
    def _infer_tags(pattern: UsagePattern) -> List[str]:
        """Infer tags from a pattern."""
        tags: List[str] = []
        for step in pattern.steps:
            if step.action.startswith("codegen"):
                tags.append("codegen")
            elif step.action.startswith("git"):
                tags.append("git")
            elif step.action.startswith("scaffold"):
                tags.append("scaffold")
            elif step.action.startswith("docs"):
                tags.append("docs")
        for cat in pattern.categories:
            tags.append(cat)
        # Dedupe
        return list(dict.fromkeys(tags))
